import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import ContextProvider from '@/context'

const ubuntuSans = Ubuntu_Sans({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // const headersObj = await headers();
    // const cookies = headersObj.get('cookie')

  return (
    <html lang="en">
      <body
        className={`${ubuntuSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
